### ISSUE TITLE
Getting started in Readme File 

### ISSUE THREAD

**Issue by richarddushime** [Profnird/codemate#2]
Hey 
Can you make the Read me file  more Clear Especially On Getting Started 
Where Npm Install And npm run test
 what will be the expected result when someone runs these commands?
Is a person suppose to create a virtualenv ?
Thank you

**Comment by Profnird** [comment]
Please there's no virtual environment to be created

**Comment by Profnird** [comment]
Please I hope you are ok with it.
after running npm run test 
the app launches into dev mode.
You can debug it inside the dev env.
